<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251116071149 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add page table and seo relations';
    }

    public function up(Schema $schema): void
    {
        // Create page table
        $this->addSql('CREATE TABLE page (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
            title VARCHAR(255) NOT NULL, 
            slug VARCHAR(255) NOT NULL UNIQUE, 
            content TEXT NULL, 
            seo_id INT NULL, 
            PRIMARY KEY (id)
        )');
        
        // Add foreign key from page to seo
        $this->addSql('ALTER TABLE page ADD CONSTRAINT FK_page_seo FOREIGN KEY (seo_id) REFERENCES seo(id) ON DELETE SET NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS page');
    }
}
