<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251116064833 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
       $this->addSql('CREATE TABLE application (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, firstname varchar(255) NOT NULL, lastname varchar(255) NOT NULL, middlename varchar(255) NOT NULL, email varchar(255) not null, phone_number varchar(255) not null, telegram_id varchar(255) null, description text null, PRIMARY KEY (id))');

    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE `application`');
    }
}
